/////////////////////////////////////////////////////////////////////////////////
//                                                                             //
// <auto-generated>                                                            //
// Date=? Machine=? User=?                                                     //
// Copyright (c) 2010-2011 Agridea, All Rights Reserved                        //
// </auto-generated>                                                           //
//                                                                             //
/////////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Data.Entity;
using System.Data.SqlClient;
//using System.Data.Entity.SqlServer;
using System.Diagnostics;
using System.Linq;
using System.Reflection;
using System.Text;
using Agridea;
using Agridea.Calendar;
using Agridea.DataRepository;
using Agridea.Diagnostics.Contracts;
using Agridea.Diagnostics.Logging;
using Agridea.Metadata;
using Agridea.News;
using Agridea.Security;
using Agridea.Service;
using Agridea.Web.UI;

namespace Agridea.Calendar
{
    public static class CalendarDomainModelContext 
    {
        #region Services
        public static void Configure(SqlServerContextBase context, DbModelBuilder modelBuilder)
        {
            #region CalendarEvent
            modelBuilder.Entity<CalendarEvent>()
                .ToTable(CodeGenerationHelper.GetTableName<CalendarEvent>());
            modelBuilder.Entity<CalendarEvent>()
                .HasKey(x => x.Id);
            modelBuilder.Entity<CalendarEvent>()
                .HasRequired(x => x.Recurrence) 
                .WithMany();
            modelBuilder.Entity<CalendarEvent>()
                .HasRequired(x => x.Status) 
                .WithMany();

            #endregion

          
            #region CalendarEventRecurrence
            modelBuilder.Entity<CalendarEventRecurrence>()
                .ToTable(CodeGenerationHelper.GetTableName<CalendarEventRecurrence>());
            modelBuilder.Entity<CalendarEventRecurrence>()
                .HasKey(x => x.Id);

            #endregion

          
            #region CalendarEventStatus
            modelBuilder.Entity<CalendarEventStatus>()
                .ToTable(CodeGenerationHelper.GetTableName<CalendarEventStatus>());
            modelBuilder.Entity<CalendarEventStatus>()
                .HasKey(x => x.Id);

            #endregion

          
        }
    	public static void AddForeignKeyIndexes(IList<NonUniqueIndex> indexes, SqlServerContextBase context)
    	{
            #region CalendarEvent
            //indexes.Add(context.GetNonUniqueIndexFor<CalendarEvent>("Recurrence_Id"));
            //indexes.Add(context.GetNonUniqueIndexFor<CalendarEvent>("Status_Id"));

            #endregion

     
            #region CalendarEventRecurrence
            //None(inheritance TPH or no *..{1,0..1} association or no index)
            #endregion

     
            #region CalendarEventStatus
            //None(inheritance TPH or no *..{1,0..1} association or no index)
            #endregion

     
        }
        public static void AddUniqueConstraints(IList<UniqueIndex> uniqueConstraints, SqlServerContextBase context)
        {
            #region CalendarEvent
            //None(inheritance TPH or no discriminant)
            #endregion

     
            #region CalendarEventRecurrence
            uniqueConstraints.Add(context.GetUniqueIndexFor<CalendarEventRecurrence>("Code"));

            #endregion

     
            #region CalendarEventStatus
            uniqueConstraints.Add(context.GetUniqueIndexFor<CalendarEventStatus>("Code"));

            #endregion

     
        }
        #endregion

    }
}
