/////////////////////////////////////////////////////////////////////////////////
//                                                                             //
// <auto-generated>                                                            //
// Date=? Machine=? User=?                                                     //
// Copyright (c) 2010-2011 Agridea, All Rights Reserved                        //
// </auto-generated>                                                           //
//                                                                             //
/////////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Data.Entity;
using System.Data.SqlClient;
//using System.Data.Entity.SqlServer;
using System.Diagnostics;
using System.Linq;
using System.Reflection;
using System.Text;
using Agridea;
using Agridea.Calendar;
using Agridea.DataRepository;
using Agridea.Diagnostics.Contracts;
using Agridea.Diagnostics.Logging;
using Agridea.Metadata;
using Agridea.News;
using Agridea.Security;
using Agridea.Service;
using Agridea.Web.UI;

namespace Agridea.Calendar
{
    [Serializable]
    public partial class CalendarEvent : PocoBase, IEquatable<CalendarEvent>
    {
        #region Primitive Properties
        public virtual string AppliesTo { get; set;}
        public virtual string Comment { get; set;}
        public virtual string Description { get; set;}
        public virtual Nullable<System.DateTime> EndDate { get; set;}
        public virtual byte[] FileData { get; set;}
        public virtual string FileName { get; set;}
        public virtual string FileType { get; set;}
        public virtual string Owner { get; set;}
        public virtual Nullable<System.DateTime> StartDate { get; set;}
        public virtual string Title { get; set;}

        #endregion

     
        #region Navigation Properties
        [Mandatory]
        public virtual CalendarEventRecurrence Recurrence  { get; set; } //CalendarEvent *==>1 CalendarEventRecurrence
        [Mandatory]
        public virtual CalendarEventStatus Status  { get; set; } //CalendarEvent *==>1 CalendarEventStatus

        #endregion

     
        #region Initialization
        public void CopyTo(CalendarEvent other)
        {
            other.AppliesTo = AppliesTo;
            other.Comment = Comment;
            other.Description = Description;
            other.EndDate = EndDate;
            other.FileData = FileData;
            other.FileName = FileName;
            other.FileType = FileType;
            other.Owner = Owner;
            other.StartDate = StartDate;
            other.Title = Title;
        }
        #endregion

     
        #region Identity
        public override string ToString()
        {
            return string.Format("[{0} AppliesTo='{1}' Comment='{2}' Description='{3}' EndDate='{4}' FileData='{5}' FileName='{6}' FileType='{7}' Owner='{8}' StartDate='{9}' Title='{10}' Recurrence.Code='{11}' Status.Code='{12}']",
                base.ToString(),
                AppliesTo,
                Comment,
                Description,
                EndDate,
                FileData,
                FileName,
                FileType,
                Owner,
                StartDate,
                Title,
                Recurrence == null ? "@null" : string.Format("{0}", Recurrence.Code),
                Status == null ? "@null" : string.Format("{0}", Status.Code));
        }
        public override int GetHashCode() { return base.GetHashCode(); }
    	public string NaturalKey()
    	{ 
    	    return 
                "No natural Key";
        }
        public override bool Equals(object other)
        {
            return Equals(other as CalendarEvent);
        }
        public bool Equals(CalendarEvent other)
        {
            if (object.ReferenceEquals(other, null)) return false;
            if (object.ReferenceEquals(this, other)) return true;
            if (!Id.Equals(other.Id)) return false;
            if (!Id.Equals(0) && Id.Equals(other.Id)) return true;
            return false;
        } 

        #endregion

     
    }
}
