/////////////////////////////////////////////////////////////////////////////////
//                                                                             //
// <auto-generated>                                                            //
// Date=? Machine=? User=?                                                     //
// Copyright (c) 2010-2011 Agridea, All Rights Reserved                        //
// </auto-generated>                                                           //
//                                                                             //
/////////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Data.Entity;
using System.Data.SqlClient;
//using System.Data.Entity.SqlServer;
using System.Diagnostics;
using System.Linq;
using System.Reflection;
using System.Text;
using Agridea;
using Agridea.Calendar;
using Agridea.DataRepository;
using Agridea.Diagnostics.Contracts;
using Agridea.Diagnostics.Logging;
using Agridea.Metadata;
using Agridea.News;
using Agridea.Security;
using Agridea.Service;
using Agridea.Web.UI;

namespace Agridea.News
{
    public class DomainModelMetadata
    {
        public IList<MetadataEntity> MetadataEntityList;
    	private IDictionary<string, MetadataEntity> metadataEntityForGuid_;
    	private MetadataEntity metadataEntity_;
    	private MetadataEntity neededMetadataEntity_;
    	private MetadataEntity needingMetadataEntity_;
    	private MetadataField metadataField_;
    	private MetadataNavigationProperty metadataNavigationProperty_;
    
    	public DomainModelMetadata()
        {
            MetadataEntityList = new List<MetadataEntity>();
    		metadataEntityForGuid_ = new Dictionary<string, MetadataEntity>();
    
    	    //No warnings
            if (metadataEntity_ == null) metadataEntity_ = null;
            if (neededMetadataEntity_ == null) neededMetadataEntity_ = null;
            if (needingMetadataEntity_ == null) needingMetadataEntity_ = null;
            if (metadataField_ == null) metadataField_ = null;
            if (metadataNavigationProperty_ == null) metadataNavigationProperty_ = null;
    
    		//Pass1 : find entities
            metadataEntity_ = new MetadataEntity
    		{
    		    Guid = "25dd71dc-129b-45af-8075-555bea385132",
    			Name = "NewsItem", 
    			Dimension = false,
    		};
    		MetadataEntityList.Add(metadataEntity_);
    		metadataEntityForGuid_.Add(metadataEntity_.Guid, metadataEntity_);
    
            metadataField_ = new MetadataField
    		{
    		    Guid = "80f45e35-658b-4fa9-a841-30e5d22c9ba8",
    			Name = "Comment", 
    			Type = "String",
    		};
    		metadataEntity_.MetadataFieldList.Add(metadataField_);
            metadataField_ = new MetadataField
    		{
    		    Guid = "0963fdad-a793-4bd3-bbbd-45199a32c06b",
    			Name = "Description", 
    			Type = "String",
    		};
    		metadataEntity_.MetadataFieldList.Add(metadataField_);
            metadataField_ = new MetadataField
    		{
    		    Guid = "fbbf1185-4ab6-49b5-82c4-d525cd664e64",
    			Name = "FileData", 
    			Type = "Binary",
    		};
    		metadataEntity_.MetadataFieldList.Add(metadataField_);
            metadataField_ = new MetadataField
    		{
    		    Guid = "d65e132b-cac4-494c-8b6d-7e746bb01c0f",
    			Name = "FileName", 
    			Type = "String",
    		};
    		metadataEntity_.MetadataFieldList.Add(metadataField_);
            metadataField_ = new MetadataField
    		{
    		    Guid = "e1c04b79-c364-44b1-b92f-202306df7a69",
    			Name = "FileType", 
    			Type = "String",
    		};
    		metadataEntity_.MetadataFieldList.Add(metadataField_);
            metadataField_ = new MetadataField
    		{
    		    Guid = "544e6386-a648-47f7-bb67-8a14e8ab73ac",
    			Name = "LinkUrl", 
    			Type = "String",
    		};
    		metadataEntity_.MetadataFieldList.Add(metadataField_);
            metadataField_ = new MetadataField
    		{
    		    Guid = "92b2bf2d-9f43-4d62-9700-69aeabd81665",
    			Name = "Title", 
    			Type = "String",
    		};
    		metadataEntity_.MetadataFieldList.Add(metadataField_);
            metadataField_ = new MetadataField
    		{
    		    Guid = "5fcf3c0b-efc3-4f5d-8db4-c2dbafd6edbb",
    			Name = "ValidityDateEnd", 
    			Type = "DateTime",
    		};
    		metadataEntity_.MetadataFieldList.Add(metadataField_);
            metadataField_ = new MetadataField
    		{
    		    Guid = "073e0793-86ab-48bc-b459-8f4442d4a109",
    			Name = "ValidityDateStart", 
    			Type = "DateTime",
    		};
    		metadataEntity_.MetadataFieldList.Add(metadataField_);
    
        	//Pass2 : add entity usages
    		metadataEntity_ = metadataEntityForGuid_["25dd71dc-129b-45af-8075-555bea385132"];  //NewsItem
    		//Needed entities
    		//Needing entities
        }
    }
}
