//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Agridea.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AgrideaCoreStrings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AgrideaCoreStrings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Agridea.Resources.AgrideaCoreStrings", typeof(AgrideaCoreStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ne peut pas être vide.
        /// </summary>
        public static string CannotBeEmpty {
            get {
                return ResourceManager.GetString("CannotBeEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cloner.
        /// </summary>
        public static string GridCloneAlternateText {
            get {
                return ResourceManager.GetString("GridCloneAlternateText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nouveau....
        /// </summary>
        public static string GridCreateAlternateText {
            get {
                return ResourceManager.GetString("GridCreateAlternateText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Supprimer.
        /// </summary>
        public static string GridDeleteAlternateText {
            get {
                return ResourceManager.GetString("GridDeleteAlternateText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Détails.
        /// </summary>
        public static string GridDetailsAlternateText {
            get {
                return ResourceManager.GetString("GridDetailsAlternateText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Editer.
        /// </summary>
        public static string GridEditAlternateText {
            get {
                return ResourceManager.GetString("GridEditAlternateText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exporter dans Excel.
        /// </summary>
        public static string GridExportToExcelAlternateText {
            get {
                return ResourceManager.GetString("GridExportToExcelAlternateText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exporter en pdf.
        /// </summary>
        public static string GridExportToPdfAlternateText {
            get {
                return ResourceManager.GetString("GridExportToPdfAlternateText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Première page.
        /// </summary>
        public static string GridFirstPage {
            get {
                return ResourceManager.GetString("GridFirstPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Données géo-référencées.
        /// </summary>
        public static string GridGeoAlternateText {
            get {
                return ResourceManager.GetString("GridGeoAlternateText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dernière page.
        /// </summary>
        public static string GridLastPage {
            get {
                return ResourceManager.GetString("GridLastPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Page suivante.
        /// </summary>
        public static string GridNextPage {
            get {
                return ResourceManager.GetString("GridNextPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} prochains éléments.
        /// </summary>
        public static string GridNextPagerElements {
            get {
                return ResourceManager.GetString("GridNextPagerElements", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aucun résultat.
        /// </summary>
        public static string GridNoResult {
            get {
                return ResourceManager.GetString("GridNoResult", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} - {1} sur {2}.
        /// </summary>
        public static string GridPaginationFormat {
            get {
                return ResourceManager.GetString("GridPaginationFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} sur {1}.
        /// </summary>
        public static string GridPaginationSimpleFormat {
            get {
                return ResourceManager.GetString("GridPaginationSimpleFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Page précédente.
        /// </summary>
        public static string GridPreviousPage {
            get {
                return ResourceManager.GetString("GridPreviousPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} éléments précédents.
        /// </summary>
        public static string GridPreviousPagerElements {
            get {
                return ResourceManager.GetString("GridPreviousPagerElements", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Réinitialiser.
        /// </summary>
        public static string GridResetAlternateText {
            get {
                return ResourceManager.GetString("GridResetAlternateText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restaurer.
        /// </summary>
        public static string GridUnDeleteAlternateText {
            get {
                return ResourceManager.GetString("GridUnDeleteAlternateText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modifier.
        /// </summary>
        public static string GridUpdateAlternateText {
            get {
                return ResourceManager.GetString("GridUpdateAlternateText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Valider.
        /// </summary>
        public static string GridValidateAlternateText {
            get {
                return ResourceManager.GetString("GridValidateAlternateText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La date de début doit précéder la date de fin.
        /// </summary>
        public static string NewsStartDateBeforEndDate {
            get {
                return ResourceManager.GetString("NewsStartDateBeforEndDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Le lien doit être de forme: http://www.domaine.com.
        /// </summary>
        public static string NewsUrlSyntax {
            get {
                return ResourceManager.GetString("NewsUrlSyntax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to L&apos;email n&apos;a pas le format souhaité, ex: pierre@domaine.ch.
        /// </summary>
        public static string SecurityEmail {
            get {
                return ResourceManager.GetString("SecurityEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La confirmation diffère du mot de passe.
        /// </summary>
        public static string SecurityPasswordConfirmation {
            get {
                return ResourceManager.GetString("SecurityPasswordConfirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Le mot de passe doit comporter entre 3 et 30 caractères.
        /// </summary>
        public static string SecurityPasswordLength {
            get {
                return ResourceManager.GetString("SecurityPasswordLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aucun utilisateur n&apos;est connecté.
        /// </summary>
        public static string SecurityPermissionNoUserConnected {
            get {
                return ResourceManager.GetString("SecurityPermissionNoUserConnected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to L&apos;utilisateur &apos;{0}&apos; n&apos;est pas autorisé à effectuer l&apos;opération &apos;{1}&apos; sur l&apos;entité &apos;{2}&apos;.
        /// </summary>
        public static string SecurityPermissionUserNotAllowedForOperationOnEntity {
            get {
                return ResourceManager.GetString("SecurityPermissionUserNotAllowedForOperationOnEntity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La création du rôle est impossible. Le rôle existe déjà.
        /// </summary>
        public static string SecurityRoleAlreadyExists {
            get {
                return ResourceManager.GetString("SecurityRoleAlreadyExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Doit comporter entre 3 et 30 caractères.
        /// </summary>
        public static string SecurityRoleNameLength {
            get {
                return ResourceManager.GetString("SecurityRoleNameLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Doit comporter entre 3 et 30 caractères.
        /// </summary>
        public static string SecurityUserNameLength {
            get {
                return ResourceManager.GetString("SecurityUserNameLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to L&apos;utilisateur doit être autorisé au moins pour une opération.
        /// </summary>
        public static string SecurityUserPermission {
            get {
                return ResourceManager.GetString("SecurityUserPermission", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to L&apos;utilisateur doit posséder au moins un rôle.
        /// </summary>
        public static string SecurityUserRole {
            get {
                return ResourceManager.GetString("SecurityUserRole", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -?-.
        /// </summary>
        public static string WebComboChoose {
            get {
                return ResourceManager.GetString("WebComboChoose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Supprimer.
        /// </summary>
        public static string WebDeleteButtonCaption {
            get {
                return ResourceManager.GetString("WebDeleteButtonCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enregistrer.
        /// </summary>
        public static string WebSaveButtonCaption {
            get {
                return ResourceManager.GetString("WebSaveButtonCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rechercher.
        /// </summary>
        public static string WebSearchButtonCaption {
            get {
                return ResourceManager.GetString("WebSearchButtonCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Envoyer un nouveau mot de passe par Email.
        /// </summary>
        public static string WebSendNewPasswordByEmailCaption {
            get {
                return ResourceManager.GetString("WebSendNewPasswordByEmailCaption", resourceCulture);
            }
        }
    }
}
