//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Agridea.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class EnumLabels {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal EnumLabels() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Agridea.Resources.EnumLabels", typeof(EnumLabels).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tous.
        /// </summary>
        public static string FarmGroup_All {
            get {
                return ResourceManager.GetString("FarmGroup_All", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exploitations stat.
        /// </summary>
        public static string FarmGroup_Hobby {
            get {
                return ResourceManager.GetString("FarmGroup_Hobby", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exploitations estivage.
        /// </summary>
        public static string FarmGroup_Summering {
            get {
                return ResourceManager.GetString("FarmGroup_Summering", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exploitations année.
        /// </summary>
        public static string FarmGroup_Yearly {
            get {
                return ResourceManager.GetString("FarmGroup_Yearly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exploitations année et stat.
        /// </summary>
        public static string FarmGroup_YearlyHobby {
            get {
                return ResourceManager.GetString("FarmGroup_YearlyHobby", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exploitations année et estivage.
        /// </summary>
        public static string FarmGroup_YearlySummering {
            get {
                return ResourceManager.GetString("FarmGroup_YearlySummering", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to --tout--.
        /// </summary>
        public static string PositiveNegativeZero_All {
            get {
                return ResourceManager.GetString("PositiveNegativeZero_All", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0.
        /// </summary>
        public static string PositiveNegativeZero_EqualToZero {
            get {
                return ResourceManager.GetString("PositiveNegativeZero_EqualToZero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &gt;0.
        /// </summary>
        public static string PositiveNegativeZero_GreaterThanZero {
            get {
                return ResourceManager.GetString("PositiveNegativeZero_GreaterThanZero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;0.
        /// </summary>
        public static string PositiveNegativeZero_LessThanZero {
            get {
                return ResourceManager.GetString("PositiveNegativeZero_LessThanZero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Non.
        /// </summary>
        public static string YesNoUnknown_No {
            get {
                return ResourceManager.GetString("YesNoUnknown_No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to --tout--.
        /// </summary>
        public static string YesNoUnknown_NoChoice {
            get {
                return ResourceManager.GetString("YesNoUnknown_NoChoice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Oui.
        /// </summary>
        public static string YesNoUnknown_Yes {
            get {
                return ResourceManager.GetString("YesNoUnknown_Yes", resourceCulture);
            }
        }
    }
}
