/////////////////////////////////////////////////////////////////////////////////
//                                                                             //
// <auto-generated>                                                            //
// Date=? Machine=? User=?                                                     //
// Copyright (c) 2010-2011 Agridea, All Rights Reserved                        //
// </auto-generated>                                                           //
//                                                                             //
/////////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Data.Entity;
using System.Data.SqlClient;
//using System.Data.Entity.SqlServer;
using System.Diagnostics;
using System.Linq;
using System.Reflection;
using System.Text;
using Agridea;
using Agridea.Calendar;
using Agridea.DataRepository;
using Agridea.Diagnostics.Contracts;
using Agridea.Diagnostics.Logging;
using Agridea.Metadata;
using Agridea.News;
using Agridea.Security;
using Agridea.Service;
using Agridea.Web.UI;

namespace Agridea.Security
{
    public class DomainModelMetadata
    {
        public IList<MetadataEntity> MetadataEntityList;
    	private IDictionary<string, MetadataEntity> metadataEntityForGuid_;
    	private MetadataEntity metadataEntity_;
    	private MetadataEntity neededMetadataEntity_;
    	private MetadataEntity needingMetadataEntity_;
    	private MetadataField metadataField_;
    	private MetadataNavigationProperty metadataNavigationProperty_;
    
    	public DomainModelMetadata()
        {
            MetadataEntityList = new List<MetadataEntity>();
    		metadataEntityForGuid_ = new Dictionary<string, MetadataEntity>();
    
    	    //No warnings
            if (metadataEntity_ == null) metadataEntity_ = null;
            if (neededMetadataEntity_ == null) neededMetadataEntity_ = null;
            if (needingMetadataEntity_ == null) needingMetadataEntity_ = null;
            if (metadataField_ == null) metadataField_ = null;
            if (metadataNavigationProperty_ == null) metadataNavigationProperty_ = null;
    
    		//Pass1 : find entities
            metadataEntity_ = new MetadataEntity
    		{
    		    Guid = "fac822a1-76b5-4767-b00a-ecd8b4d3a9a8",
    			Name = "Permission", 
    			Dimension = false,
    		};
    		MetadataEntityList.Add(metadataEntity_);
    		metadataEntityForGuid_.Add(metadataEntity_.Guid, metadataEntity_);
    
            metadataField_ = new MetadataField
    		{
    		    Guid = "54f4ab4e-33f4-4118-9070-b2a3249be1a2",
    			Name = "Description", 
    			Type = "String",
    		};
    		metadataEntity_.MetadataFieldList.Add(metadataField_);
            metadataField_ = new MetadataField
    		{
    		    Guid = "e1688d1a-8c71-40fc-b335-92e80733cef8",
    			Name = "ItemName", 
    			Type = "String",
    		};
    		metadataEntity_.MetadataFieldList.Add(metadataField_);
            metadataNavigationProperty_ = new MetadataNavigationProperty
    		{
    		    Guid = "ae34122f-f35a-48c3-b1c2-b7519c371d9c",
    			Name = "Role", 
    			Type = "Role",
    			FromMultiplicity = MultiplicityTypes.ZeroOrMany,
    			ToMultiplicity = MultiplicityTypes.OneExactly,
    		};
    		metadataEntity_.MetadataNavigationPropertyList.Add(metadataNavigationProperty_);
            metadataEntity_ = new MetadataEntity
    		{
    		    Guid = "3031ac25-21a0-464d-b7e0-87ed36ed2074",
    			Name = "Role", 
    			Dimension = false,
    		};
    		MetadataEntityList.Add(metadataEntity_);
    		metadataEntityForGuid_.Add(metadataEntity_.Guid, metadataEntity_);
    
            metadataField_ = new MetadataField
    		{
    		    Guid = "9c6c5701-c029-4dd5-b7dc-9cd4c0370f23",
    			Name = "CanAccessAllFarms", 
    			Type = "Boolean",
    		};
    		metadataEntity_.MetadataFieldList.Add(metadataField_);
            metadataField_ = new MetadataField
    		{
    		    Guid = "f578ac41-3d3c-4fb6-a955-ce50fd959fd7",
    			Name = "Description", 
    			Type = "String",
    		};
    		metadataEntity_.MetadataFieldList.Add(metadataField_);
            metadataField_ = new MetadataField
    		{
    		    Guid = "b9bf1aec-0960-4c5e-bf0c-4519ca1defa4",
    			Name = "IsWebApi", 
    			Type = "Boolean",
    		};
    		metadataEntity_.MetadataFieldList.Add(metadataField_);
            metadataField_ = new MetadataField
    		{
    		    Guid = "12b6f78d-9eed-45df-a944-006dac050134",
    			Name = "Name", 
    			Type = "String",
    		};
    		metadataEntity_.MetadataFieldList.Add(metadataField_);
            metadataNavigationProperty_ = new MetadataNavigationProperty
    		{
    		    Guid = "f22a322e-b09d-44df-a349-d2e308c1b622",
    			Name = "PermissionList", 
    			Type = "Permission",
    			FromMultiplicity = MultiplicityTypes.OneExactly,
    			ToMultiplicity = MultiplicityTypes.ZeroOrMany,
    		};
    		metadataEntity_.MetadataNavigationPropertyList.Add(metadataNavigationProperty_);
            metadataNavigationProperty_ = new MetadataNavigationProperty
    		{
    		    Guid = "2a00b1fa-44b3-4206-bccf-8bf952f5f783",
    			Name = "UserRoleList", 
    			Type = "UserRole",
    			FromMultiplicity = MultiplicityTypes.OneExactly,
    			ToMultiplicity = MultiplicityTypes.ZeroOrMany,
    		};
    		metadataEntity_.MetadataNavigationPropertyList.Add(metadataNavigationProperty_);
            metadataEntity_ = new MetadataEntity
    		{
    		    Guid = "f1534bae-9c18-40c3-bd19-c0975ea34767",
    			Name = "User", 
    			Dimension = false,
    		};
    		MetadataEntityList.Add(metadataEntity_);
    		metadataEntityForGuid_.Add(metadataEntity_.Guid, metadataEntity_);
    
            metadataField_ = new MetadataField
    		{
    		    Guid = "24ada0c8-47d6-4172-bc55-fdedeb091712",
    			Name = "Blocked", 
    			Type = "Boolean",
    		};
    		metadataEntity_.MetadataFieldList.Add(metadataField_);
            metadataField_ = new MetadataField
    		{
    		    Guid = "5e012c34-a094-4f79-8992-6840d84be5be",
    			Name = "Email", 
    			Type = "String",
    		};
    		metadataEntity_.MetadataFieldList.Add(metadataField_);
            metadataField_ = new MetadataField
    		{
    		    Guid = "8a3f4546-8520-4985-b7a0-1c8fe3413e2e",
    			Name = "LastActivityDate", 
    			Type = "DateTime",
    		};
    		metadataEntity_.MetadataFieldList.Add(metadataField_);
            metadataField_ = new MetadataField
    		{
    		    Guid = "14dfcc22-c229-41ce-a58b-c1f3893e748b",
    			Name = "LastLoginDate", 
    			Type = "DateTime",
    		};
    		metadataEntity_.MetadataFieldList.Add(metadataField_);
            metadataField_ = new MetadataField
    		{
    		    Guid = "dbc4479e-25e3-4776-892f-2494a2007769",
    			Name = "LastPasswordChangeDate", 
    			Type = "DateTime",
    		};
    		metadataEntity_.MetadataFieldList.Add(metadataField_);
            metadataField_ = new MetadataField
    		{
    		    Guid = "d998e77e-4fc1-4b6c-93f1-351eecd01fe2",
    			Name = "Password", 
    			Type = "String",
    		};
    		metadataEntity_.MetadataFieldList.Add(metadataField_);
            metadataField_ = new MetadataField
    		{
    		    Guid = "042e729f-2c9d-4c94-8ed9-edd86315cc95",
    			Name = "SuperUser", 
    			Type = "Boolean",
    		};
    		metadataEntity_.MetadataFieldList.Add(metadataField_);
            metadataField_ = new MetadataField
    		{
    		    Guid = "9a74e02e-329b-4418-b24a-9b31ec7fe279",
    			Name = "UserName", 
    			Type = "String",
    		};
    		metadataEntity_.MetadataFieldList.Add(metadataField_);
            metadataNavigationProperty_ = new MetadataNavigationProperty
    		{
    		    Guid = "ecee210c-964c-4047-990c-84a41a97fbf2",
    			Name = "UserRoleList", 
    			Type = "UserRole",
    			FromMultiplicity = MultiplicityTypes.OneExactly,
    			ToMultiplicity = MultiplicityTypes.ZeroOrMany,
    		};
    		metadataEntity_.MetadataNavigationPropertyList.Add(metadataNavigationProperty_);
            metadataEntity_ = new MetadataEntity
    		{
    		    Guid = "70eed306-3d3d-40dc-a96e-65c7859a4b2e",
    			Name = "UserRole", 
    			Dimension = false,
    		};
    		MetadataEntityList.Add(metadataEntity_);
    		metadataEntityForGuid_.Add(metadataEntity_.Guid, metadataEntity_);
    
            metadataField_ = new MetadataField
    		{
    		    Guid = "3fe6d416-6e35-427c-9da7-e2f81d0d4423",
    			Name = "Comment", 
    			Type = "String",
    		};
    		metadataEntity_.MetadataFieldList.Add(metadataField_);
            metadataField_ = new MetadataField
    		{
    		    Guid = "008753fc-ba9f-4677-ac27-632836688dc3",
    			Name = "CommitmentDate", 
    			Type = "DateTime",
    		};
    		metadataEntity_.MetadataFieldList.Add(metadataField_);
            metadataField_ = new MetadataField
    		{
    		    Guid = "ecc5fa8c-9003-4ba8-97f4-6c1b1e675781",
    			Name = "FarmGroup", 
    			Type = "FarmGroup",
    		};
    		metadataEntity_.MetadataFieldList.Add(metadataField_);
            metadataNavigationProperty_ = new MetadataNavigationProperty
    		{
    		    Guid = "236b6137-f1c0-4e15-9f03-af5718671c4c",
    			Name = "Role", 
    			Type = "Role",
    			FromMultiplicity = MultiplicityTypes.ZeroOrMany,
    			ToMultiplicity = MultiplicityTypes.OneExactly,
    		};
    		metadataEntity_.MetadataNavigationPropertyList.Add(metadataNavigationProperty_);
            metadataNavigationProperty_ = new MetadataNavigationProperty
    		{
    		    Guid = "3a1a1941-e91c-478b-baa8-bedcd77e3d6a",
    			Name = "User", 
    			Type = "User",
    			FromMultiplicity = MultiplicityTypes.ZeroOrMany,
    			ToMultiplicity = MultiplicityTypes.OneExactly,
    		};
    		metadataEntity_.MetadataNavigationPropertyList.Add(metadataNavigationProperty_);
    
        	//Pass2 : add entity usages
    		metadataEntity_ = metadataEntityForGuid_["fac822a1-76b5-4767-b00a-ecd8b4d3a9a8"];  //Permission
    		//Needed entities
    		    neededMetadataEntity_ = metadataEntityForGuid_["3031ac25-21a0-464d-b7e0-87ed36ed2074"]; //Role
    			metadataEntity_.UsedEntityList.Add(neededMetadataEntity_);
    		//Needing entities
    		    needingMetadataEntity_ = metadataEntityForGuid_["3031ac25-21a0-464d-b7e0-87ed36ed2074"]; //Role
    			metadataEntity_.UsingEntityList.Add(needingMetadataEntity_);
    		metadataEntity_ = metadataEntityForGuid_["3031ac25-21a0-464d-b7e0-87ed36ed2074"];  //Role
    		//Needed entities
    		    neededMetadataEntity_ = metadataEntityForGuid_["fac822a1-76b5-4767-b00a-ecd8b4d3a9a8"]; //Permission
    			metadataEntity_.UsedEntityList.Add(neededMetadataEntity_);
    		    neededMetadataEntity_ = metadataEntityForGuid_["70eed306-3d3d-40dc-a96e-65c7859a4b2e"]; //UserRole
    			metadataEntity_.UsedEntityList.Add(neededMetadataEntity_);
    		//Needing entities
    		    needingMetadataEntity_ = metadataEntityForGuid_["fac822a1-76b5-4767-b00a-ecd8b4d3a9a8"]; //Permission
    			metadataEntity_.UsingEntityList.Add(needingMetadataEntity_);
    		    needingMetadataEntity_ = metadataEntityForGuid_["70eed306-3d3d-40dc-a96e-65c7859a4b2e"]; //UserRole
    			metadataEntity_.UsingEntityList.Add(needingMetadataEntity_);
    		metadataEntity_ = metadataEntityForGuid_["f1534bae-9c18-40c3-bd19-c0975ea34767"];  //User
    		//Needed entities
    		    neededMetadataEntity_ = metadataEntityForGuid_["70eed306-3d3d-40dc-a96e-65c7859a4b2e"]; //UserRole
    			metadataEntity_.UsedEntityList.Add(neededMetadataEntity_);
    		//Needing entities
    		    needingMetadataEntity_ = metadataEntityForGuid_["70eed306-3d3d-40dc-a96e-65c7859a4b2e"]; //UserRole
    			metadataEntity_.UsingEntityList.Add(needingMetadataEntity_);
    		metadataEntity_ = metadataEntityForGuid_["70eed306-3d3d-40dc-a96e-65c7859a4b2e"];  //UserRole
    		//Needed entities
    		    neededMetadataEntity_ = metadataEntityForGuid_["3031ac25-21a0-464d-b7e0-87ed36ed2074"]; //Role
    			metadataEntity_.UsedEntityList.Add(neededMetadataEntity_);
    		    neededMetadataEntity_ = metadataEntityForGuid_["f1534bae-9c18-40c3-bd19-c0975ea34767"]; //User
    			metadataEntity_.UsedEntityList.Add(neededMetadataEntity_);
    		//Needing entities
    		    needingMetadataEntity_ = metadataEntityForGuid_["3031ac25-21a0-464d-b7e0-87ed36ed2074"]; //Role
    			metadataEntity_.UsingEntityList.Add(needingMetadataEntity_);
    		    needingMetadataEntity_ = metadataEntityForGuid_["f1534bae-9c18-40c3-bd19-c0975ea34767"]; //User
    			metadataEntity_.UsingEntityList.Add(needingMetadataEntity_);
        }
    }
}
