// ------------------------------------------------------------------------------
//  <auto-generated>
//    Generated by Xsd2Code. Version 3.4.0.32989
//    <NameSpace>Agridea.Acorda.Acorda2.Blw</NameSpace><Collection>List</Collection><codeType>CSharp</codeType><EnableDataBinding>False</EnableDataBinding><EnableLazyLoading>False</EnableLazyLoading><TrackingChangesEnable>False</TrackingChangesEnable><GenTrackingClasses>False</GenTrackingClasses><HidePrivateFieldInIDE>False</HidePrivateFieldInIDE><EnableSummaryComment>True</EnableSummaryComment><VirtualProp>False</VirtualProp><IncludeSerializeMethod>False</IncludeSerializeMethod><UseBaseClass>False</UseBaseClass><GenBaseClass>False</GenBaseClass><GenerateCloneMethod>False</GenerateCloneMethod><GenerateDataContracts>False</GenerateDataContracts><CodeBaseTag>Net40</CodeBaseTag><SerializeMethodName>Serialize</SerializeMethodName><DeserializeMethodName>Deserialize</DeserializeMethodName><SaveToFileMethodName>SaveToFile</SaveToFileMethodName><LoadFromFileMethodName>LoadFromFile</LoadFromFileMethodName><GenerateXMLAttributes>True</GenerateXMLAttributes><OrderXMLAttrib>False</OrderXMLAttrib><EnableEncoding>False</EnableEncoding><AutomaticProperties>False</AutomaticProperties><GenerateShouldSerialize>False</GenerateShouldSerialize><DisableDebug>False</DisableDebug><PropNameSpecified>Default</PropNameSpecified><Encoder>UTF8</Encoder><CustomUsings></CustomUsings><ExcludeIncludedTypes>True</ExcludeIncludedTypes><EnableInitializeFields>True</EnableInitializeFields>
//  </auto-generated>
// ------------------------------------------------------------------------------
namespace Agridea.Acorda.Agis
{
    using System;
    using System.Diagnostics;
    using System.Xml.Serialization;
    using System.Collections;
    using System.Xml.Schema;
    using System.ComponentModel;
    using System.Collections.Generic;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.admin.ch/xmlns/DataTypes/evd/ecoEtho/2")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://www.admin.ch/xmlns/DataTypes/evd/ecoEtho/2", IsNullable=false)]
    public partial class ecoEthoRegistrationRoot {
        
        private string registrationYearField;
        
        private cantonFlAbbreviationType cantonFlAbbreviationField;
        
        private List<ecoEthoRegistrationRootFarm> farmField;
        
        /// <summary>
        /// ecoEthoRegistrationRoot class constructor
        /// </summary>
        public ecoEthoRegistrationRoot() {
            this.farmField = new List<ecoEthoRegistrationRootFarm>();
        }
        
        [System.Xml.Serialization.XmlElementAttribute(DataType="gYear")]
        public string registrationYear {
            get {
                return this.registrationYearField;
            }
            set {
                this.registrationYearField = value;
            }
        }
        
        public cantonFlAbbreviationType cantonFlAbbreviation {
            get {
                return this.cantonFlAbbreviationField;
            }
            set {
                this.cantonFlAbbreviationField = value;
            }
        }
        
        [System.Xml.Serialization.XmlElementAttribute("farm")]
        public List<ecoEthoRegistrationRootFarm> farm {
            get {
                return this.farmField;
            }
            set {
                this.farmField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.admin.ch/xmlns/DataTypes/evd/ecoEtho/2")]
    public partial class ecoEthoRegistrationRootFarm {
        
        private ecoEthoRegistrationRootFarmGeneralData generalDataField;
        
        private List<ecoEthoRegistrationRootFarmProgramRegistration> registrationsField;
        
        /// <summary>
        /// ecoEthoRegistrationRootFarm class constructor
        /// </summary>
        public ecoEthoRegistrationRootFarm() {
            this.registrationsField = new List<ecoEthoRegistrationRootFarmProgramRegistration>();
            this.generalDataField = new ecoEthoRegistrationRootFarmGeneralData();
        }
        
        public ecoEthoRegistrationRootFarmGeneralData generalData {
            get {
                return this.generalDataField;
            }
            set {
                this.generalDataField = value;
            }
        }
        
        [System.Xml.Serialization.XmlArrayItemAttribute("programRegistration", IsNullable=false)]
        public List<ecoEthoRegistrationRootFarmProgramRegistration> registrations {
            get {
                return this.registrationsField;
            }
            set {
                this.registrationsField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.admin.ch/xmlns/DataTypes/evd/ecoEtho/2")]
    public partial class ecoEthoRegistrationRootFarmGeneralData {
        
        private namedFarmIdType localFarmIdField;
        
        private namedPersonIdType localPersonIdField;
        
        private List<organizationNameType> controlOrganizationNameField;
        
        /// <summary>
        /// ecoEthoRegistrationRootFarmGeneralData class constructor
        /// </summary>
        public ecoEthoRegistrationRootFarmGeneralData() {
            this.controlOrganizationNameField = new List<organizationNameType>();
            this.localPersonIdField = new namedPersonIdType();
            this.localFarmIdField = new namedFarmIdType();
        }
        
        public namedFarmIdType localFarmId {
            get {
                return this.localFarmIdField;
            }
            set {
                this.localFarmIdField = value;
            }
        }
        
        public namedPersonIdType localPersonId {
            get {
                return this.localPersonIdField;
            }
            set {
                this.localPersonIdField = value;
            }
        }
        
        [System.Xml.Serialization.XmlElementAttribute("controlOrganizationName")]
        public List<organizationNameType> controlOrganizationName {
            get {
                return this.controlOrganizationNameField;
            }
            set {
                this.controlOrganizationNameField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.admin.ch/xmlns/DataTypes/evd/ecoEtho/2")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://www.admin.ch/xmlns/DataTypes/evd/ecoEtho/2", IsNullable=false)]
    public enum organizationNameType {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("KS-AFAPI-FR")]
        KSAFAPIFR,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("KS-AGRICON-AG")]
        KSAGRICONAG,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("KS-AGRIPIGE-GE")]
        KSAGRIPIGEGE,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("KS-AGRISPEA-TI")]
        KSAGRISPEATI,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("KS-AGROCONTROL-ZH")]
        KSAGROCONTROLZH,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("KS-AGROCONTROLL-BL/BS/SO")]
        KSAGROCONTROLLBLBSSO,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("KS-AJAPI-JU")]
        KSAJAPIJU,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("KS-ANAPI-NE")]
        KSANAPINE,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("KS-AVPI-VS")]
        KSAVPIVS,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("KS-BIOINSPECTA")]
        KSBIOINSPECTA,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("KS-BIOTESTAGRO")]
        KSBIOTESTAGRO,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("KS-CAREA-BE")]
        KSCAREABE,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("KS-COBRA-VD")]
        KSCOBRAVD,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("KS-KDSNZ-NW/SZ/ZG")]
        KSKDSNZNWSZZG,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("KS-KOL-TG")]
        KSKOLTG,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("KS-KUL-BE")]
        KSKULBE,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("KS-KUT-SG")]
        KSKUTSG,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("KS-LIA-AI/AR")]
        KSLIAAIAR,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("KS-OLK-VS")]
        KSOLKVS,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("KS-QUALINOVA-LU")]
        KSQUALINOVALU,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("LWA-AG")]
        LWAAG,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("LWA-AI")]
        LWAAI,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("LWA-AR")]
        LWAAR,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("LWA-BE")]
        LWABE,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("LWA-BL/BS")]
        LWABLBS,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("LWA-FL")]
        LWAFL,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("LWA-FR")]
        LWAFR,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("LWA-GE")]
        LWAGE,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("LWA-GL")]
        LWAGL,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("LWA-GR")]
        LWAGR,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("LWA-JU")]
        LWAJU,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("LWA-LU")]
        LWALU,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("LWA-NE")]
        LWANE,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("LWA-NW")]
        LWANW,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("LWA-OW")]
        LWAOW,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("LWA-SG")]
        LWASG,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("LWA-SH")]
        LWASH,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("LWA-SO")]
        LWASO,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("LWA-SZ")]
        LWASZ,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("LWA-TG")]
        LWATG,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("LWA-TI")]
        LWATI,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("LWA-UR")]
        LWAUR,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("LWA-VD")]
        LWAVD,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("LWA-VS")]
        LWAVS,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("LWA-ZG")]
        LWAZG,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("LWA-ZH")]
        LWAZH,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("KS-ECOPREST-VD")]
        KSECOPRESTVD,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("KS-PI3LACS-VD/NE")]
        KSPI3LACSVDNE,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("KS-VITIVAL-VD")]
        KSVITIVALVD,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("99")]
        Item99,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.admin.ch/xmlns/DataTypes/evd/ecoEtho/2")]
    public partial class ecoEthoRegistrationRootFarmProgramRegistration {
        
        private programNameType programNameField;
        
        private registrationTypeType programTypeField;
        
        public programNameType programName {
            get {
                return this.programNameField;
            }
            set {
                this.programNameField = value;
            }
        }
        
        public registrationTypeType programType {
            get {
                return this.programTypeField;
            }
            set {
                this.programTypeField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.admin.ch/xmlns/DataTypes/evd/ecoEtho/2")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://www.admin.ch/xmlns/DataTypes/evd/ecoEtho/2", IsNullable=false)]
    public enum programNameType {
        
        /// <remarks/>
        oeln,
        
        /// <remarks/>
        oelnGem1,
        
        /// <remarks/>
        oelnGem2,
        
        /// <remarks/>
        oelnGem3,
        
        /// <remarks/>
        bffQua1,
        
        /// <remarks/>
        bffQua2,
        
        /// <remarks/>
        bffVer,
        
        /// <remarks/>
        bioGanz,
        
        /// <remarks/>
        bioOhneDK,
        
        /// <remarks/>
        bioNurDK,
        
        /// <remarks/>
        bioUmst,
        
        /// <remarks/>
        extenso,
        
        /// <remarks/>
        gmf,
        
        /// <remarks/>
        btsRin1,
        
        /// <remarks/>
        btsRin2,
        
        /// <remarks/>
        btsRin3,
        
        /// <remarks/>
        btsRin4,
        
        /// <remarks/>
        btsRin6,
        
        /// <remarks/>
        btsRin7,
        
        /// <remarks/>
        btsRin8,
        
        /// <remarks/>
        btsPfe1,
        
        /// <remarks/>
        btsPfe2,
        
        /// <remarks/>
        btsZie1,
        
        /// <remarks/>
        btsZie2,
        
        /// <remarks/>
        btsSch1,
        
        /// <remarks/>
        btsSch2,
        
        /// <remarks/>
        btsSch3,
        
        /// <remarks/>
        btsSch4,
        
        /// <remarks/>
        btsSch5,
        
        /// <remarks/>
        btsKan1,
        
        /// <remarks/>
        btsKan2,
        
        /// <remarks/>
        btsGef1,
        
        /// <remarks/>
        btsGef2,
        
        /// <remarks/>
        btsGef3,
        
        /// <remarks/>
        btsGef4,
        
        /// <remarks/>
        btsGef5,
        
        /// <remarks/>
        rausRin1,
        
        /// <remarks/>
        rausRin2,
        
        /// <remarks/>
        rausRin3,
        
        /// <remarks/>
        rausRin4,
        
        /// <remarks/>
        rausRin5,
        
        /// <remarks/>
        rausRin6,
        
        /// <remarks/>
        rausRin7,
        
        /// <remarks/>
        rausRin8,
        
        /// <remarks/>
        rausRin9,
        
        /// <remarks/>
        rausPfe1,
        
        /// <remarks/>
        rausPfe2,
        
        /// <remarks/>
        rausPfe3,
        
        /// <remarks/>
        rausZie1,
        
        /// <remarks/>
        rausZie2,
        
        /// <remarks/>
        rausScha1,
        
        /// <remarks/>
        rausScha2,
        
        /// <remarks/>
        rausScha3,
        
        /// <remarks/>
        rausSch1,
        
        /// <remarks/>
        rausSch2,
        
        /// <remarks/>
        rausSch3,
        
        /// <remarks/>
        rausSch4,
        
        /// <remarks/>
        rausSch5,
        
        /// <remarks/>
        rausKan1,
        
        /// <remarks/>
        rausKan2,
        
        /// <remarks/>
        rausGef1,
        
        /// <remarks/>
        rausGef2,
        
        /// <remarks/>
        rausGef3,
        
        /// <remarks/>
        rausGef4,
        
        /// <remarks/>
        rausGef5,
        
        /// <remarks/>
        reAub,
        
        /// <remarks/>
        reBobDi,
        
        /// <remarks/>
        reBobSt,
        
        /// <remarks/>
        reBobMu,
        
        /// <remarks/>
        reBobHv,
        
        /// <remarks/>
        reApp,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.admin.ch/xmlns/DataTypes/evd/ecoEtho/2")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://www.admin.ch/xmlns/DataTypes/evd/ecoEtho/2", IsNullable=false)]
    public enum registrationTypeType {
        
        /// <remarks/>
        weiter,
        
        /// <remarks/>
        neu,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("nicht zugeteilt")]
        nichtzugeteilt,
    }
}
