// ------------------------------------------------------------------------------
//  <auto-generated>
//    Originally generated by Xsd2Code. Version 3.3.0.31926
//    <NameSpace>Agridea.Acorda2.Sipa</NameSpace><Collection>Array</Collection><codeType>CSharp</codeType><EnableDataBinding>False</EnableDataBinding><EnableLazyLoading>True</EnableLazyLoading><TrackingChangesEnable>False</TrackingChangesEnable><GenTrackingClasses>False</GenTrackingClasses><HidePrivateFieldInIDE>False</HidePrivateFieldInIDE><EnableSummaryComment>True</EnableSummaryComment><VirtualProp>False</VirtualProp><IncludeSerializeMethod>True</IncludeSerializeMethod><UseBaseClass>True</UseBaseClass><GenBaseClass>True</GenBaseClass><GenerateCloneMethod>False</GenerateCloneMethod><GenerateDataContracts>False</GenerateDataContracts><CodeBaseTag>Net40</CodeBaseTag><SerializeMethodName>Serialize</SerializeMethodName><DeserializeMethodName>Deserialize</DeserializeMethodName><SaveToFileMethodName>SaveToFile</SaveToFileMethodName><LoadFromFileMethodName>LoadFromFile</LoadFromFileMethodName><GenerateXMLAttributes>True</GenerateXMLAttributes><AutomaticProperties>False</AutomaticProperties><GenerateShouldSerialize>False</GenerateShouldSerialize><DisableDebug>False</DisableDebug><PropNameSpecified>Default</PropNameSpecified><CustomUsings></CustomUsings><ExcludeIncludedTypes>False</ExcludeIncludedTypes><EnableInitializeFields>False</EnableInitializeFields>
//  </auto-generated>
// ------------------------------------------------------------------------------
using System;
using System.Text;
using System.Xml.Schema;
using System.Xml.Serialization;

namespace Agridea.Acorda.Agis
{
    [XmlType(AnonymousType = true, Namespace = "http://www.admin.ch/xmlns/DataTypes/evd/register/1")]
    [XmlRoot(Namespace = "http://www.admin.ch/xmlns/DataTypes/evd/register/1", IsNullable = false)]
    public class registerRoot : BlwDataBase<registerRoot>
    {
        public registerRoot()
        {
            this.AddNamespace("blw-register", "http://www.admin.ch/xmlns/DataTypes/evd/register/1");
            this.AddNamespace("eCH-0010ext", "http://www.ech.ch/xmlns/eCH-0010/3");
            this.AddNamespace("eCH-0046ext", "http://www.ech.ch/xmlns/eCH-0046/1");
            this.MessageType = 4000;
        }

        [XmlAttribute("schemaLocation", Namespace = XmlSchema.InstanceNamespace)]
        public string xsiSchemaLocation = "http://www.admin.ch/xmlns/DataTypes/evd/register/1 http://www.admin.ch/xmlns/DataTypes/evd/register/1/register-1-96.xsd";

        /// <summary>
        /// container for all persons of a canton
        /// </summary>
        [XmlArrayItem("person", IsNullable = false)]
        public personType[] personRoot { get; set; }

        /// <summary>
        /// container for all farms of a canton
        /// </summary>
        [XmlArrayItem("farm", IsNullable = false)]
        public farmType[] farmRoot { get; set; }

        /// <summary>
        /// container for all register data TVD informations of a canton
        /// </summary>
        [XmlArrayItem("tvdInfo", IsNullable = false)]
        public tvdInfoType[] tvdInfoRoot { get; set; }

        /// <summary>
        /// container for all ID change requests of a canton
        /// </summary>
        public idChangeType idChangeRoot { get; set; }

        /// <summary>
        /// container for all relationships between persons / farms of a canton
        /// </summary>
        public relationshipType relationshipRoot { get; set; }

        /// <summary>
        /// indicates the data owner canton
        /// </summary>
        public cantonFlAbbreviationType cantonFlAbbreviation { get; set; }
    }

    #region farmRoot

    [XmlType(AnonymousType = true, Namespace = "http://www.admin.ch/xmlns/DataTypes/evd/register/1")]
    [XmlRoot(Namespace = "http://www.admin.ch/xmlns/DataTypes/evd/register/1", IsNullable = false)]
    public class farmRoot : BlwDataBase<farmRoot>
    {
        /// <summary>
        /// single farm container
        /// </summary>
        [XmlElement("farm")]
        public farmType[] farm { get; set; }

        public cantonFlAbbreviationType cantonFlAbbreviation { get; set; }
    }

    [XmlType(Namespace = "http://www.admin.ch/xmlns/DataTypes/evd/register/1")]
    public class farmType : BlwDataBase<farmType>
    {
        public farmIdentificationType farmIdentification { get; set; }

        [XmlElement("farmType")]
        public farmTypeType farmType1 { get; set; }

        public Register.addressInformationType addressInformation { get; set; }

        [XmlElement(DataType = "integer")]
        public string coordinateX { get; set; }

        [XmlElement(DataType = "integer")]
        public string coordinateY { get; set; }

        [XmlElement(DataType = "integer")]
        public string altitude { get; set; }

        [XmlElement(DataType = "integer")]
        public string zone { get; set; }

        [XmlElement(DataType = "integer")]
        public string area { get; set; }

        [XmlElement(DataType = "token")]
        public string tvdNr { get; set; }

        [XmlElement(DataType = "token")]
        public string locationCommunalName { get; set; }

        [XmlElement(DataType = "token")]
        public string locationCommunalNumber { get; set; }
    }

    [XmlType(Namespace = "http://www.admin.ch/xmlns/DataTypes/evd/register/1")]
    public class farmIdentificationType : BlwDataBase<farmIdentificationType>
    {
        public uidStructureType uidFarmId { get; set; }

        public namedFarmIdType localFarmId { get; set; }

        [XmlElement("otherFarmId")]
        public namedFarmIdType[] otherFarmId { get; set; }
    }

    [XmlType(Namespace = "http://www.admin.ch/xmlns/DataTypes/evd/register/1")]
    public class uidStructureType : BlwDataBase<uidStructureType>
    {
        public uidFarmIdCategoryType uidFarmIdCategory { get; set; }

        [XmlElement(DataType = "nonNegativeInteger")]
        public string uidNumber { get; set; }
    }

    [XmlType(Namespace = "http://www.admin.ch/xmlns/DataTypes/evd/register/1")]
    public enum uidFarmIdCategoryType
    {
        /// <remarks/>
        CHE,
    }

    [XmlType(Namespace = "http://www.ech.ch/xmlns/eCH-0010/3", IncludeInSchema = false)]
    public enum ZipCodeChoices
    {
        /// <remarks/>
        foreignZipCode,

        /// <remarks/>
        swissZipCode,
    }

    [XmlType(Namespace = "http://www.admin.ch/xmlns/DataTypes/evd/register/1")]
    public enum farmTypeType
    {
        /// <remarks/>
        [XmlEnum("01")]
        Item01,

        /// <remarks/>
        [XmlEnum("02")]
        Item02,

        /// <remarks/>
        [XmlEnum("03")]
        Item03,

        /// <remarks/>
        [XmlEnum("04")]
        Item04,

        /// <remarks/>
        [XmlEnum("05")]
        Item05,

        /// <remarks/>
        [XmlEnum("06")]
        Item06,

        /// <remarks/>
        [XmlEnum("08")]
        Item08,

        /// <remarks/>
        [XmlEnum("09")]
        Item09,

        /// <remarks/>
        [XmlEnum("10")]
        Item10,

        /// <remarks/>
        [XmlEnum("11")]
        Item11,

        /// <remarks/>
        [XmlEnum("12")]
        Item12,

        /// <remarks/>
        [XmlEnum("13")]
        Item13,

        /// <remarks/>
        [XmlEnum("14")]
        Item14,

        /// <remarks/>
        [XmlEnum("15")]
        Item15,

        /// <remarks/>
        [XmlEnum("16")]
        Item16,

        /// <remarks/>
        [XmlEnum("20")]
        Item20,

        /// <remarks/>
        [XmlEnum("99")]
        Item99,
    }

    #endregion farmRoot

    #region personRoot

    [XmlType(AnonymousType = true, Namespace = "http://www.admin.ch/xmlns/DataTypes/evd/register/1")]
    [XmlRoot(Namespace = "http://www.admin.ch/xmlns/DataTypes/evd/register/1", IsNullable = false)]
    public class personRoot : BlwDataBase<personRoot>
    {
        /// <summary>
        /// single person container
        /// </summary>
        [XmlElement("person")]
        public personType[] person { get; set; }

        public cantonFlAbbreviationType cantonFlAbbreviation { get; set; }
    }

    [XmlType(Namespace = "http://www.admin.ch/xmlns/DataTypes/evd/register/1")]
    public class personType : BlwDataBase<personType>
    {
        public personIdentificationType personIdentification { get; set; }

        [XmlElement(DataType = "token")]
        public string jobTitle { get; set; }

        public Register.legalFormType legalForm { get; set; }

        public datePartiallyKnownType foundationDate { get; set; }

        [XmlElement(DataType = "token")]
        public string residenceCommunalName { get; set; }

        [XmlElement(DataType = "token")]
        public string residenceCommunalNumber { get; set; }

        [XmlElement(DataType = "token")]
        public string languageOfCorrespondance { get; set; }

        public contactType contact { get; set; }
    }

    [XmlType(Namespace = "http://www.admin.ch/xmlns/DataTypes/evd/register/1")]
    public class datePartiallyKnownType : BlwDataBase<datePartiallyKnownType>
    {
        [XmlElement("year", typeof(string), DataType = "gYear")]
        [XmlElement("yearMonth", typeof(string), DataType = "gYearMonth")]
        [XmlElement("yearMonthDay", typeof(DateTime), DataType = "date")]
        [XmlChoiceIdentifier("ItemElementName")]
        public object Item { get; set; }

        [XmlIgnore]
        public Register.ItemChoiceType ItemElementName { get; set; }
    }

    [XmlType(Namespace = "http://www.ech.ch/xmlns/eCH-0046/1")]
    public class contactType : BlwDataBase<contactType>
    {
        public namedPersonIdType1 localID { get; set; }

        public addressType address { get; set; }

        public emailType email { get; set; }

        [XmlElement("phone")]
        public phoneType[] phone { get; set; }

        public internetType internet { get; set; }
    }

    [XmlType(TypeName = "namedPersonIdType", Namespace = "http://www.ech.ch/xmlns/eCH-0044/1")]
    public class namedPersonIdType1 : BlwDataBase<namedPersonIdType1>
    {
        [XmlElement(DataType = "token")]
        public string personIdCategory { get; set; }

        [XmlElement(DataType = "token")]
        public string personId { get; set; }
    }

    [XmlType(Namespace = "http://www.ech.ch/xmlns/eCH-0046/1")]
    public class addressType : BlwDataBase<addressType>
    {
        public string addressCategory { get; set; }

        public mailAddressType postalAddress { get; set; }
    }

    [XmlType(Namespace = "http://www.ech.ch/xmlns/eCH-0010/3")]
    public class mailAddressType : BlwDataBase<mailAddressType>
    {
        [XmlElement("organisation", typeof(organisationMailAddressInfoType))]
        [XmlElement("person", typeof(personMailAddressInfoType))]
        public object Item { get; set; }

        public Register.addressInformationType addressInformation { get; set; }
    }

    [XmlType(Namespace = "http://www.ech.ch/xmlns/eCH-0010/3")]
    public class organisationMailAddressInfoType : BlwDataBase<organisationMailAddressInfoType>
    {
        [XmlElement(DataType = "token")]
        public string organisationName { get; set; }

        [XmlElement(DataType = "token")]
        public string organisationNameAddOn1 { get; set; }

        [XmlElement(DataType = "token")]
        public string organisationNameAddOn2 { get; set; }

        [XmlElement(DataType = "token")]
        public string firstName { get; set; }

        [XmlElement(DataType = "token")]
        public string lastName { get; set; }
    }

    [XmlType(Namespace = "http://www.ech.ch/xmlns/eCH-0010/3")]
    public class personMailAddressInfoType : BlwDataBase<personMailAddressInfoType>
    {
        [XmlIgnore]
        public bool mrMrsSpecified { get; set; }

        [XmlElement(DataType = "token")]
        public string firstName { get; set; }

        [XmlElement(DataType = "token")]
        public string lastName { get; set; }

        public mrMrsExtendedType mrMrsExtended { get; set; }

        [XmlIgnore]
        public bool mrMrsExtendedSpecified { get; set; }
    }

    [XmlType(Namespace = "http://www.ech.ch/xmlns/eCH-0010/3")]
    public enum mrMrsType
    {
        /// <remarks/>
        [XmlEnum("1")]
        Item1,

        /// <remarks/>
        [XmlEnum("2")]
        Item2,

        /// <remarks/>
        [XmlEnum("3")]
        Item3,
    }

    [XmlType(Namespace = "http://www.ech.ch/xmlns/eCH-0010/3")]
    public enum mrMrsExtendedType
    {
        /// <remarks/>
        [XmlEnum("1")]
        Item1,

        /// <remarks/>
        [XmlEnum("2")]
        Item2,

        /// <remarks/>
        [XmlEnum("3")]
        Item3,

        /// <remarks/>
        [XmlEnum("4")]
        Item4,
    }

    [XmlType(Namespace = "http://www.ech.ch/xmlns/eCH-0046/1")]
    public class emailType : BlwDataBase<emailType>
    {
        public string emailCategory { get; set; }

        public string emailAddress { get; set; }
    }

    [XmlType(Namespace = "http://www.ech.ch/xmlns/eCH-0046/1")]
    public class phoneType : BlwDataBase<phoneType>
    {
        public string phoneCategory { get; set; }

        public string phoneNumber { get; set; }
    }

    [XmlType(Namespace = "http://www.ech.ch/xmlns/eCH-0046/1")]
    public class internetType : BlwDataBase<internetType>
    {
        public string internetCategory { get; set; }

        [XmlElement(DataType = "token")]
        public string internetAddress { get; set; }
    }

    #endregion personRoot

    #region idChangeRoot

    [XmlType(AnonymousType = true, Namespace = "http://www.admin.ch/xmlns/DataTypes/evd/register/1")]
    [XmlRoot(Namespace = "http://www.admin.ch/xmlns/DataTypes/evd/register/1", IsNullable = false)]
    public class idChangeRoot : BlwDataBase<idChangeRoot>
    {
        public idChangeType idChange { get; set; }

        public cantonFlAbbreviationType cantonFlAbbreviation { get; set; }
    }

    [XmlType(Namespace = "http://www.admin.ch/xmlns/DataTypes/evd/register/1")]
    public class idChangeType : BlwDataBase<idChangeType>
    {
        [XmlElement("idChangePerson")]
        public idChangeTypeIdChangePerson[] idChangePerson { get; set; }

        [XmlElement("idChangeFarm")]
        public idChangeTypeIdChangeFarm[] idChangeFarm { get; set; }
    }

    [XmlType(AnonymousType = true, Namespace = "http://www.admin.ch/xmlns/DataTypes/evd/register/1")]
    public class idChangeTypeIdChangePerson : BlwDataBase<idChangeTypeIdChangePerson>
    {
        public namedPersonIdType oldPersonId { get; set; }

        public namedPersonIdType newPersonId { get; set; }
    }

    [XmlType(AnonymousType = true, Namespace = "http://www.admin.ch/xmlns/DataTypes/evd/register/1")]
    public class idChangeTypeIdChangeFarm : BlwDataBase<idChangeTypeIdChangeFarm>
    {
        public namedFarmIdType oldFarmId { get; set; }

        public namedFarmIdType newFarmId { get; set; }
    }

    #endregion idChangeRoot

    #region relationshipRoot

    [XmlType(AnonymousType = true, Namespace = "http://www.admin.ch/xmlns/DataTypes/evd/register/1")]
    [XmlRoot(Namespace = "http://www.admin.ch/xmlns/DataTypes/evd/register/1", IsNullable = false)]
    public class relationshipRoot : BlwDataBase<relationshipRoot>
    {
        public relationshipType relationship { get; set; }

        public cantonFlAbbreviationType cantonFlAbbreviation { get; set; }
    }

    [XmlType(Namespace = "http://www.admin.ch/xmlns/DataTypes/evd/register/1")]
    public class relationshipType : BlwDataBase<relationshipType>
    {
        [XmlElement("relationshipF2P")]
        public relationshipTypeRelationshipF2P[] relationshipF2P { get; set; }

        [XmlElement("relationshipP2P")]
        public relationshipTypeRelationshipP2P[] relationshipP2P { get; set; }

        [XmlElement("relationshipF2F")]
        public relationshipTypeRelationshipF2F[] relationshipF2F { get; set; }
    }

    [XmlType(AnonymousType = true, Namespace = "http://www.admin.ch/xmlns/DataTypes/evd/register/1")]
    public class relationshipTypeRelationshipF2P : BlwDataBase<relationshipTypeRelationshipF2P>
    {
        public namedFarmIdType farmReference { get; set; }

        public namedPersonIdType personReference { get; set; }

        public relationshipTypeType relationshipType { get; set; }
    }

    [XmlType(Namespace = "http://www.admin.ch/xmlns/DataTypes/evd/register/1")]
    public enum relationshipTypeType
    {
        /// <remarks/>
        [XmlEnum("01")]
        Item01,

        /// <remarks/>
        [XmlEnum("02")]
        Item02,

        /// <remarks/>
        [XmlEnum("99")]
        Item99,
    }

    [XmlType(AnonymousType = true, Namespace = "http://www.admin.ch/xmlns/DataTypes/evd/register/1")]
    public class relationshipTypeRelationshipP2P : BlwDataBase<relationshipTypeRelationshipP2P>
    {
        public namedPersonIdType personRefParent { get; set; }

        public namedPersonIdType personRefChild { get; set; }
    }

    [XmlType(AnonymousType = true, Namespace = "http://www.admin.ch/xmlns/DataTypes/evd/register/1")]
    public class relationshipTypeRelationshipF2F : BlwDataBase<relationshipTypeRelationshipF2F>
    {
        public namedFarmIdType farmRefParent { get; set; }

        public namedFarmIdType farmRefChild { get; set; }
    }

    #endregion relationshipRoot

    #region tvdInfoRoot

    [XmlType(AnonymousType = true, Namespace = "http://www.admin.ch/xmlns/DataTypes/evd/register/1")]
    [XmlRoot(Namespace = "http://www.admin.ch/xmlns/DataTypes/evd/register/1", IsNullable = false)]
    public class tvdInfoRoot : BlwDataBase<tvdInfoRoot>
    {
        /// <summary>
        /// single register data TVD information container
        /// </summary>
        [XmlElement("tvdInfo")]
        public tvdInfoType[] tvdInfo { get; set; }

        public cantonFlAbbreviationType cantonFlAbbreviation { get; set; }
    }

    [XmlType(Namespace = "http://www.admin.ch/xmlns/DataTypes/evd/register/1")]
    public class tvdInfoType : BlwDataBase<tvdInfoType>
    {
        [XmlElement(DataType = "token")]
        public string kt_ID_B { get; set; }

        [XmlElement(DataType = "token")]
        public string tvdNr { get; set; }

        public zeroOneType status { get; set; }

        [XmlIgnore]
        public DateTime validFrom { get; set; }

        [XmlElement(ElementName = "validFrom", DataType = "string")]
        public string validFromWrapper
        {
            get { return this.validFrom.ToXmlDateTimeWithoutMillisecondsAndGmt(); }
            set { this.validFrom = value.ParseForDateTime(); }
        }

        public zero123Type statusReason { get; set; }

        public zeroOneType cattle { get; set; }

        public zero123Type usageCattle { get; set; }

        public zeroOneType pigs { get; set; }

        public zeroOneType sheep { get; set; }

        public zeroOneType goats { get; set; }

        public zeroOneType camelid { get; set; }

        public zeroOneType game { get; set; }

        public zeroOneType equidae { get; set; }

        public zeroOneType fish { get; set; }

        public zeroOneType poultry { get; set; }

        public bees012Type bees { get; set; }

        public override string ToString()
        {
            return String.Format("[{0} Ktidb='{1}' TvdNr='{2}' Status='{3}' StatusReason='{4}' Animals='{5}']",
                base.ToString(), kt_ID_B, tvdNr,
                ((int)status).ToString(), ((int)statusReason).ToString(), Animals);
        }

        [XmlIgnore]
        protected string Animals
        {
            get
            {
                StringBuilder sb = new StringBuilder("[");
                if (cattle == zeroOneType.Item1) sb.Append("cattle,");
                if (pigs == zeroOneType.Item1) sb.Append("pigs,");
                if (sheep == zeroOneType.Item1) sb.Append("sheep,");
                if (goats == zeroOneType.Item1) sb.Append("goats,");
                if (camelid == zeroOneType.Item1) sb.Append("camelid,");
                if (game == zeroOneType.Item1) sb.Append("game,");
                if (equidae == zeroOneType.Item1) sb.Append("equidae,");
                if (fish == zeroOneType.Item1) sb.Append("fish,");
                if (poultry == zeroOneType.Item1) sb.Append("poultry,");
                if (bees != bees012Type.Item0) sb.Append("bees,");
                return sb.ToString().TrimEnd(',') + "]";
            }
        }
    }

    [XmlType(Namespace = "http://www.admin.ch/xmlns/DataTypes/evd/register/1")]
    public enum zeroOneType
    {
        /// <remarks/>
        [XmlEnum("0")]
        Item0,

        /// <remarks/>
        [XmlEnum("1")]
        Item1,
    }

    [XmlType(Namespace = "http://www.admin.ch/xmlns/DataTypes/evd/register/1")]
    public enum zero123Type
    {
        /// <remarks/>
        [XmlEnum("0")]
        Item0,

        /// <remarks/>
        [XmlEnum("1")]
        Item1,

        /// <remarks/>
        [XmlEnum("2")]
        Item2,

        /// <remarks/>
        [XmlEnum("3")]
        Item3,
    }

    [XmlType(Namespace = "http://www.admin.ch/xmlns/DataTypes/evd/register/1")]
    public enum bees012Type
    {
        /// <remarks>
        /// keine Bienen
        /// </remarks>
        [XmlEnum("0")]
        Item0,

        /// <remarks>
        /// unbesetzter Bienenstand
        /// </remarks>
        [XmlEnum("1")]
        Item1,

        /// <remarks>
        /// besetzter Bienenstand
        /// </remarks>
        [XmlEnum("2")]
        Item2,
    }

    #endregion tvdInfoRoot

    #region Common

    [XmlType(Namespace = "http://www.admin.ch/xmlns/DataTypes/evd/register/1")]
    public class namedFarmIdType : BlwDataBase<namedFarmIdType>
    {
        private string farmIdCategoryField;
        private string farmIdField;

        [XmlElement(DataType = "token")]
        public string farmIdCategory
        {
            get { return farmIdCategoryField; }
            set { farmIdCategoryField = value; }
        }

        [XmlElement(DataType = "token")]
        public string farmId
        {
            get { return farmIdField; }
            set { farmIdField = value; }
        }
    }

    [XmlType(Namespace = "http://www.admin.ch/xmlns/DataTypes/evd/register/1")]
    public class personIdentificationType : BlwDataBase<personIdentificationType>
    {
        private namedPersonIdType localPersonIdField;
        private namedPersonIdType[] otherPersonIdField;

        public namedPersonIdType localPersonId
        {
            get { return localPersonIdField; }
            set { localPersonIdField = value; }
        }

        [XmlElement("OtherPersonId")]
        public namedPersonIdType[] OtherPersonId
        {
            get { return otherPersonIdField; }
            set { otherPersonIdField = value; }
        }
    }

    [XmlType(Namespace = "http://www.admin.ch/xmlns/DataTypes/evd/register/1")]
    public class namedPersonIdType : BlwDataBase<namedPersonIdType>
    {
        private string personIdCategoryField;
        private string personIdField;

        [XmlElement(DataType = "token")]
        public string personIdCategory
        {
            get { return personIdCategoryField; }
            set { personIdCategoryField = value; }
        }

        [XmlElement(DataType = "token")]
        public string personId
        {
            get { return personIdField; }
            set { personIdField = value; }
        }
    }

    #endregion Common
}

namespace Agridea.Acorda.Agis.Register
{
    [XmlType(Namespace = "http://www.admin.ch/xmlns/DataTypes/evd/register/1")]
    public enum legalFormType
    {
        /// <remarks/>
        [XmlEnum("01")]
        Item01,

        /// <remarks/>
        [XmlEnum("02")]
        Item02,

        /// <remarks/>
        [XmlEnum("03")]
        Item03,

        /// <remarks/>
        [XmlEnum("04")]
        Item04,

        /// <remarks/>
        [XmlEnum("05")]
        Item05,

        /// <remarks/>
        [XmlEnum("06")]
        Item06,

        /// <remarks/>
        [XmlEnum("07")]
        Item07,

        /// <remarks/>
        [XmlEnum("08")]
        Item08,

        /// <remarks/>
        [XmlEnum("09")]
        Item09,

        /// <remarks/>
        [XmlEnum("10")]
        Item10,

        /// <remarks/>
        [XmlEnum("24")]
        Item24,

        /// <remarks/>
        [XmlEnum("25")]
        Item25,

        /// <remarks/>
        [XmlEnum("30")]
        Item30,

        /// <remarks/>
        [XmlEnum("31")]
        Item31,

        /// <remarks/>
        [XmlEnum("32")]
        Item32,

        /// <remarks/>
        [XmlEnum("33")]
        Item33,

        /// <remarks/>
        [XmlEnum("34")]
        Item34,

        /// <remarks/>
        [XmlEnum("99")]
        Item99,
    }

    [XmlType(Namespace = "http://www.admin.ch/xmlns/DataTypes/evd/register/1", IncludeInSchema = false)]
    public enum ItemChoiceType
    {
        /// <remarks/>
        year,

        /// <remarks/>
        yearMonth,

        /// <remarks/>
        yearMonthDay,
    }

    [XmlType(Namespace = "http://www.ech.ch/xmlns/eCH-0010/3")]
    public class addressInformationType : BlwDataBase<addressInformationType>
    {
        [XmlElement(DataType = "token")]
        public string addressLine1 { get; set; }

        public bool ShouldSerializeaddressLine1()
        {
            return !String.IsNullOrEmpty(addressLine1);
        }

        [XmlElement(DataType = "token")]
        public string addressLine3 { get; set; }

        [XmlElement(DataType = "token")]
        public string street { get; set; }

        [XmlElement(DataType = "token")]
        public string houseNumber { get; set; }

        public uint postOfficeBoxNumber { get; set; }

        [XmlIgnore]
        public bool postOfficeBoxNumberSpecified { get; set; }

        [XmlElement(DataType = "token")]
        public string postOfficeBoxText { get; set; }

        [XmlElement(DataType = "token")]
        public string town { get; set; }

        [XmlElement("foreignZipCode", typeof(string), DataType = "token")]
        [XmlElement("swissZipCode", typeof(uint))]
        [XmlChoiceIdentifier("ZipCodeChoice")]
        public object[] ZipCode { get; set; }

        [XmlElement("ZipCodeChoice")]
        [XmlIgnore]
        public ZipCodeChoices[] ZipCodeChoice { get; set; }

        [XmlElement(DataType = "token")]
        public string country { get; set; }
    }
}